### ISSUE TITLE
`jwt-auth:access-token` config error should not show stack trace

### ISSUE THREAD

**Issue by shazron** [adobe/aio-cli-plugin-jwt-auth#43]
```
Error: missing config data: jwt-auth
    at getAccessToken (~/git/adobe/aio-cli-plugin-jwt-auth/src/commands/jwt-auth/access-token.js:42:27)
    at AccessTokenCommand.run (~/git/adobe/aio-cli-plugin-jwt-auth/src/commands/jwt-auth/access-token.js:105:20)
    at AccessTokenCommand._run (~/git/adobe/aio-cli-plugin-jwt-auth/node_modules/@oclif/command/lib/command.js:44:31)
    at <anonymous>
```

**Comment by shazron** [comment]
This line should print `this.error(error.message)`: https://github.com/adobe/aio-cli-plugin-jwt-auth/blob/04ea118aa7a6de174c2dab4606a75e09e6c8f07c/src/commands/jwt-auth/access-token.js#L108
